version: 2
updates:
  - package-ecosystem: "gomod"
    cooldown:
      default-days: 7
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      go-all:
        patterns: ["*"]
        update-types:
          - "minor"
          - "patch"
      go-major:
        patterns: ["*"]
        update-types:
          - "major"
      go-security:
        applies-to: security-updates
        patterns: ["*"]
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "github-actions"
    cooldown:
      default-days: 7
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      actions-all:
        patterns: ["*"]
        update-types:
          - "minor"
          - "patch"
      actions-major:
        patterns: ["*"]
        update-types:
          - "major"
      actions-security:
        applies-to: security-updates
        patterns: ["*"]
        update-types:
          - "minor"
          - "patch"
